#!/bin/bash

if [ -z $1 ]; then
	echo 'Usage: tinypng <input> <output>'
	exit
fi

if [ -z $2 ]; then
	echo 'Usage: tinypng <input> <output>'
	exit
fi

if [ ! -f ~/.tinypng_apikey ]; then
	echo 'Put your TinyPNG API key into ~/.tinypng_apikey'
 	exit
fi	

api_key=$(cat ~/.tinypng_apikey)

function upload {
	echo $(curl https://api.tinify.com/shrink \
		--user api:$api_key \
		--dump-header /dev/stdout \
		--data-binary @$1 | grep Location | awk '{print $2}' | dos2unix )
}

function download {
	curl $1 \
		--user api:$api_key \
		--output $2
}

download $(upload $1) $2
